require(VAM)
set.seed(3)
simCMPM<-sim.vam(  ~ (ARA1(.9) | Weibull(.001,2.5)) & (ARAInf(.7) | AtIntensity(0.2)))
simData<-simulate(simCMPM, Size>=10)
save(simData,file="simCMPM.RData")
print(head(simData))
print(table(simData$Type))
mleCMPM <- mle.vam( Time & Type ~ (ARA1(.9) | Weibull(.001,2.5)) & (ARAInf(.7) | AtIntensity(0.2)), data=simData)
print(coef(mleCMPM))
print(ls(mleCMPM))
print(mleCMPM$optim)
theta<-c(.001,2.5,.9,.7)
print(logLik(mleCMPM,theta,TRUE,FALSE,FALSE))
print(logLik(mleCMPM,theta,FALSE,TRUE,FALSE))
print(contrast(mleCMPM,theta,TRUE,FALSE,FALSE))
print(contrast(mleCMPM,theta,FALSE,TRUE,FALSE))